package ru.deepthreads.api.value

import com.google.rpc.Code
import throwApiException

enum class ApiCode(val grpc: Int) {
    INCORRECT_NICKNAME_FORMAT(Code.INVALID_ARGUMENT_VALUE),
    INCORRECT_DEEP_ID_FORMAT(Code.INVALID_ARGUMENT_VALUE),
    INCORRECT_PASSWORD_FORMAT(Code.INVALID_ARGUMENT_VALUE),
    NONEXISTENT_ACCOUNT(Code.NOT_FOUND_VALUE),
    TAKEN_DEEP_ID(Code.INVALID_ARGUMENT_VALUE),
    WRONG_PASSWORD(Code.PERMISSION_DENIED_VALUE),
    INVALID_TOKEN(Code.PERMISSION_DENIED_VALUE),
    EMPTY_TOKEN(Code.PERMISSION_DENIED_VALUE),
    NOT_FOUND(Code.NOT_FOUND_VALUE),
    EMPTY_NICKNAME(Code.INVALID_ARGUMENT_VALUE),
    CANNOT_EDIT_DEEP_ID(Code.PERMISSION_DENIED_VALUE),
    EMPTY_AVATAR(Code.INVALID_ARGUMENT_VALUE),
    ALREADY_SUBSCRIBED(Code.PERMISSION_DENIED_VALUE),
    NOT_SUBSCRIBED(Code.INVALID_ARGUMENT_VALUE),
    INTERNAL_SERVER_ERROR(Code.UNKNOWN_VALUE);

    fun throwSelf(message: String) = throwApiException(this, message)
}
